version: '3.0'
services:
  proxy:
    restart: always
    build:
      context: ./nginx
    depends_on:
      - api
    ports:
      - '80:3000'
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - mongo
    volumes:
      - '/app/node_modules'
      - './:/app'
  mongo:
    image: mongo:5.0
    ports:
      - '27017'
    volumes:
      - 'todo_api_volume:/data/db'
volumes:
  todo_api_volume:
